-- migrate:up

INSERT INTO `refSections` (`Id`, `Name`) VALUES (1,'No Major Glitches');
INSERT INTO `refSections` (`Id`, `Name`) VALUES (2,'Major Glitches');
INSERT INTO `refSections` (`Id`, `Name`) VALUES (3,'Misc. Categories');

INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (1,'Any%',NULL,NULL,1,0,1,1,0,0,0,NULL,1,'https://wiki.supermetroid.run/Any%25');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (2,'Low%',NULL,NULL,1,0,1,2,0,0,0,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (3,'100%',NULL,NULL,1,0,1,3,0,0,0,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (4,'Reverse Boss Order','RBO',NULL,1,1,1,4,0,0,1,'RBO',1,'https://wiki.supermetroid.run/RBO');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (5,'Map','OneHundredPercentMap',3,NULL,1,1,2,0,0,1,NULL,1,'https://wiki.supermetroid.run/100%25_Map_Completion');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (6,'Ceres Escape','Ceres',NULL,3,1,1,1,0,1,0,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (7,'Spore Spawn','SporeSpawnRTA',NULL,3,1,1,2,0,0,1,NULL,1,'https://wiki.supermetroid.run/SSRTA');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (9,'Low%',NULL,NULL,2,0,1,2,0,0,0,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (10,'Classic','GTClassic',28,NULL,1,1,2,0,0,1,NULL,1,'https://wiki.supermetroid.run/GT_Classic');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (11,'Spacetime','AnyPercentGTCode',28,NULL,1,1,1,0,0,1,NULL,1,'https://wiki.supermetroid.run/Any%25_GT_Code');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (12,'12% (All Bosses)','LowPercentAllBosses',9,NULL,1,1,2,0,0,1,NULL,1,'https://wiki.supermetroid.run/12%25');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (13,'Zebes Escape','ZebesEscape',0,3,0,0,999,0,1,0,NULL,0,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (14,'Crocomire','CrocomireRTA',0,3,1,1,3,0,0,1,NULL,1,'https://wiki.supermetroid.run/Crocomire_RTA');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (15,'Game Time','AnyPercentGameTime',1,NULL,1,1,2,1,0,1,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (16,'Real Time','AnyPercentRealTime',1,NULL,1,1,1,0,0,1,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (17,'PAL','PALAnyPercentRealTime',1,NULL,1,1,3,0,0,1,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (18,'Ice','LowPercentIce',2,NULL,1,1,1,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_Ice');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (19,'Speed','LowPercentSpeed',2,NULL,1,1,2,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_Speed');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (20,'Icebooster','LowPercentIceBooster',2,NULL,1,1,3,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_Iceboost');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (21,'xIce','LowPercentXIce',2,NULL,1,1,4,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_xIce');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (22,'Items','OneHundredPercent',3,NULL,1,1,1,0,0,1,NULL,1,'https://wiki.supermetroid.run/100%25');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (23,'Any%','AnyPercentGlitched',NULL,2,1,1,1,0,0,1,NULL,1,'https://wiki.supermetroid.run/Any%25_Glitched');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (24,'0%','LowPercentGlitched',9,NULL,1,1,1,0,0,1,NULL,1,'https://wiki.supermetroid.run/0%25');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (25,'Iceboots (PAL)','PALLowPercentIceboots',2,NULL,1,1,6,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_Iceboots');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (26,'Speedboots (PAL)','PALLowPercentSpeedBoots',2,NULL,1,1,7,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_Speedboots');
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (27,'Power Bombs Any%','PowerBombs',NULL,NULL,0,0,999,0,0,1,NULL,0,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (28,'GT Code',NULL,NULL,2,0,1,3,0,0,0,NULL,1,NULL);
INSERT INTO `tblCategories` (`Id`, `Name`, `UrlName`, `ParentId`, `SectionId`, `AllowSubmission`, `Visible`, `DisplayOrder`, `GameTime`, `EscapeGameTime`, `RealTime`, `ShortName`, `Enabled`, `WikiUrl`) VALUES (29,'Chargeless','LowPercentChargeless',2,NULL,1,1,5,0,0,1,NULL,1,'https://wiki.supermetroid.run/14%25_Chargeless');

-- migrate:down

DELETE FROM `tblCategories` WHERE `Id` BETWEEN 1 AND 29;
DELETE FROM `refSections` WHERE `Id` BETWEEN 1 AND 3;
